name: Build Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Show branch name
        run: echo ${{ github.ref_name }}

      - name: Checkout submodules
        run: |
          git submodule sync
          git submodule init
          git submodule update --force --recursive --init --remote

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

      - name: Show all .nupkg files within Release folders in workspace
        run: find $GITHUB_WORKSPACE -type d -name "Release" -exec find {} -type f -name "*.nupkg" \;
